# Generated by Django 5.2.6 on 2025-09-13 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='allocation.batch'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='allocation.orderline'),
        ),
    ]
