name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Update dependencies
      run: |
        uv sync --upgrade
        uv lock --upgrade
    
    - name: Check if there are changes
      id: changes
      run: |
        if git diff --quiet uv.lock pyproject.toml; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Run tests with updated dependencies
      if: steps.changes.outputs.changed == 'true'
      run: |
        uv sync --dev
        uv run python cosmic/manage.py check
        uv run pytest --tb=short
      env:
        DJANGO_SETTINGS_MODULE: cosmic.settings.test
        PYTHONPATH: .:cosmic
    
    - name: Create Pull Request
      if: steps.changes.outputs.changed == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "🔄 Automated dependency updates"
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates generated by GitHub Actions.
          
          ### Changes
          - Updated dependencies in `uv.lock`
          - Potentially updated version constraints in `pyproject.toml`
          
          ### Testing
          - ✅ Django system checks passed
          - ✅ All tests passed
          
          Please review the changes and merge if appropriate.
        branch: automated-dependency-updates
        delete-branch: true
